pipeline {
    agent any
    

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/anish612/Jenkins-pipeline-Django.git']])
            }
        }

        stage('Build') {
            steps {
                sh 'pip install -r /myproject/requirements.txt'
                sh 'python manage.py test'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'pip install -r requirements.txt'
                    sh 'python manage.py runserver 0.0.0.0:8000'
                }
            }
        }
    }
}
